version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: gcr.io/${PROJECT_ID}/mpp-backend:latest
    environment:
      - DEBUG=0
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL:-sqlite:///db.sqlite3}
    volumes:
      - sqlite_data:/app
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: gcr.io/${PROJECT_ID}/mpp-frontend:latest
    environment:
      - NEXT_PUBLIC_API_URL=${API_URL:-http://backend:8080}
    ports:
      - "3000:8080"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

volumes:
  sqlite_data: