# Generated by Django 5.1.6 on 2025-03-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="datetime",
        ),
        migrations.AddField(
            model_name="booking",
            name="end_date",
            field=models.DateField(default="2023-05-05"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="start_date",
            field=models.DateField(default="2024-05-05"),
            preserve_default=False,
        ),
    ]
