# Generated by Django 5.1.6 on 2025-05-03 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_operationlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonitoredUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flagged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitor_entry",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
